In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer ,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [17]:
df = pd.read_csv("train.csv" , usecols=['Age' , 'Survived' , 'Fare' , 'Pclass'])

In [18]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [19]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [20]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [21]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [29]:
X_train ,X_test , y_train , y_test = train_test_split(X , y ,test_size=0.25,random_state=4)

In [46]:
knn = KNNImputer(n_neighbors=5 , weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [47]:
X_train_trf

array([[ 2.    , 52.    , 13.5   ],
       [ 3.    , 20.    ,  7.2292],
       [ 3.    , 22.    ,  7.75  ],
       ...,
       [ 2.    , 31.    , 10.5   ],
       [ 1.    , 56.    , 30.6958],
       [ 2.    , 32.5   , 30.0708]])

In [48]:
pd.DataFrame(X_train_trf , columns = X_train.columns)

     Pclass   Age     Fare
0       2.0  52.0  13.5000
1       3.0  20.0   7.2292
2       3.0  22.0   7.7500
3       3.0  36.0   7.8958
4       3.0  50.0   8.0500
..      ...   ...      ...
663     3.0  40.0  27.9000
664     3.0  29.0  15.2458
665     2.0  31.0  10.5000
666     1.0  56.0  30.6958
667     2.0  32.5  30.0708

[668 rows x 3 columns]

In [49]:
lr = LogisticRegression()

lr.fit(X_train_trf , y_train)
y_pred = lr.predict(X_test_trf)

accuracy_score(y_test , y_pred)

0.7533632286995515

Comparing with mean imputation

In [50]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [51]:
lr = LogisticRegression()

lr.fit(X_train_trf2 , y_train)
y_pred2 =lr.predict(X_test_trf2)
accuracy_score(y_test , y_pred2)

0.7443946188340808